### ISSUE TITLE
 [ONNXRuntimeError] : 7 : INVALID_PROTOBUF

### ISSUE THREAD

**Issue by fueroz** [FurkanGozukara/Stable-Diffusion#16]
Hello! Thanks for great app, hope ill can try it) I ran into a problem. After choosing a photo and target, after choosing a save directory for the file, I get this error:
 sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\Elizaveta/.insightface\models\buffalo_l\det_10g.onnx failed:Protobuf parsing failed.
What can I do for fixing it?

**Comment by fueroz** [comment]
full log:
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Elizaveta/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Exception in thread Thread-2 (<lambda>):
Traceback (most recent call last):
  File "C:\Users\Elizaveta\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Elizaveta\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\deepface\roop\roop\ui.py", line 304, in <lambda>
    start_button = create_button(window, "Start", lambda: [save_file(save_file_handler, target_path.get()), preview_thread(lambda: start(update_preview))])
  File "C:\deepface\roop\roop\core.py", line 174, in start
    test_face = get_face_single(cv2.imread(args.source_img))
  File "C:\deepface\roop\roop\analyser.py", line 16, in get_face_single
    face = get_face_analyser().get(img_data)
  File "C:\deepface\roop\roop\analyser.py", line 10, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=roop.globals.providers)
  File "C:\Users\Elizaveta\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\app\face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
  File "C:\Users\Elizaveta\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "C:\Users\Elizaveta\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "C:\Users\Elizaveta\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "C:\Users\Elizaveta\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\Elizaveta\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\Elizaveta/.insightface\models\buffalo_l\det_10g.onnx failed:Protobuf parsing failed.
