### ISSUE TITLE
i canot start roop

### ISSUE THREAD

**Issue by chemistiano** [FurkanGozukara/Stable-Diffusion#25]
(venv) E:\Deepface\roop>python run.py --keep-frames --keep-fps --core 1
Traceback (most recent call last):
  File "E:\Deepface\roop\run.py", line 3, in <module>
    from roop import core
  File "E:\Deepface\roop\roop\core.py", line 16, in <module>
    import onnxruntime
ModuleNotFoundError: No module named 'onnxruntime'

**Comment by FurkanGozukara** [comment]
hello. did you install c++ tools before installing roop?
