### ISSUE TITLE
ModuleNotFoundError: No module named 'gradio'

### ISSUE THREAD

**Issue by gotanidea** [FurkanGozukara/Stable-Diffusion#33]
Hi, thanks for the steps and the tutorial. I followed the instructions on GitHub and YouTube, but I got the same error with both methods:

_ModuleNotFoundError: No module named 'gradio'_

Here is the text from the Command Prompt, after I followed the instructions on GitHub:

```
Microsoft Windows [Version 10.0.22621.2283]
(c) Microsoft Corporation. All rights reserved.

D:\Installers>git clone https://github.com/facebookresearch/audiocraft
Cloning into 'audiocraft'...
remote: Enumerating objects: 953, done.
remote: Counting objects: 100% (237/237), done.
remote: Compressing objects: 100% (122/122), done.
remote: Total 953 (delta 153), reused 143 (delta 114), pack-reused 716Receiving objects:  99% (944/953), 848.00 KiB | 1.64 MiB/s
Receiving objects: 100% (953/953), 1.74 MiB | 2.27 MiB/s, done.
Resolving deltas: 100% (480/480), done.

D:\Installers>cd audiocraft

D:\Installers\audiocraft>python -m venv venv

D:\Installers\audiocraft>cd venv

D:\Installers\audiocraft\venv>cd scripts

D:\Installers\audiocraft\venv\Scripts>activate

(venv) D:\Installers\audiocraft\venv\Scripts>cd ..

(venv) D:\Installers\audiocraft\venv>cd ..

(venv) D:\Installers\audiocraft>pip install -e .
Obtaining file:///D:/Installers/audiocraft
  Preparing metadata (setup.py) ... done
Collecting av
  Using cached av-10.0.0-cp310-cp310-win_amd64.whl (25.3 MB)
Collecting einops
  Using cached einops-0.7.0-py3-none-any.whl (44 kB)
Collecting flashy>=0.0.1
  Using cached flashy-0.0.2.tar.gz (72 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting hydra-core>=1.1
  Using cached hydra_core-1.3.2-py3-none-any.whl (154 kB)
Collecting hydra_colorlog
  Using cached hydra_colorlog-1.2.0-py3-none-any.whl (3.6 kB)
Collecting julius
  Using cached julius-0.2.7.tar.gz (59 kB)
  Preparing metadata (setup.py) ... done
Collecting num2words
  Using cached num2words-0.5.12-py3-none-any.whl (125 kB)
Collecting numpy
  Using cached numpy-1.26.0-cp310-cp310-win_amd64.whl (15.8 MB)
Collecting sentencepiece
  Using cached sentencepiece-0.1.99-cp310-cp310-win_amd64.whl (977 kB)
Collecting spacy==3.5.2
  Using cached spacy-3.5.2-cp310-cp310-win_amd64.whl (12.2 MB)
Collecting torch>=2.0.0
  Downloading torch-2.1.0-cp310-cp310-win_amd64.whl (192.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.3/192.3 MB 4.9 MB/s eta 0:00:00
Collecting torchaudio>=2.0.0
  Downloading torchaudio-2.1.0-cp310-cp310-win_amd64.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 6.4 MB/s eta 0:00:00
Collecting huggingface_hub
  Using cached huggingface_hub-0.17.3-py3-none-any.whl (295 kB)
Collecting tqdm
  Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Collecting transformers>=4.31.0
  Using cached transformers-4.34.0-py3-none-any.whl (7.7 MB)
Collecting xformers
  Using cached xformers-0.0.22-cp310-cp310-win_amd64.whl (97.6 MB)
Collecting demucs
  Using cached demucs-4.0.1.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... done
Collecting librosa
  Using cached librosa-0.10.1-py3-none-any.whl (253 kB)
Collecting gradio
  Using cached gradio-3.47.1-py3-none-any.whl (20.3 MB)
Collecting torchmetrics
  Using cached torchmetrics-1.2.0-py3-none-any.whl (805 kB)
Collecting encodec
  Using cached encodec-0.1.1.tar.gz (3.7 MB)
  Preparing metadata (setup.py) ... done
Collecting protobuf
  Using cached protobuf-4.24.4-cp310-abi3-win_amd64.whl (430 kB)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting pathy>=0.10.0
  Using cached pathy-0.10.2-py3-none-any.whl (48 kB)
Collecting packaging>=20.0
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
Collecting langcodes<4.0.0,>=3.2.0
  Using cached langcodes-3.3.0-py3-none-any.whl (181 kB)
Collecting cymem<2.1.0,>=2.0.2
  Using cached cymem-2.0.8-cp310-cp310-win_amd64.whl (39 kB)
Requirement already satisfied: setuptools in d:\installers\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft==1.0.0) (65.5.0)
Collecting srsly<3.0.0,>=2.4.3
  Using cached srsly-2.4.8-cp310-cp310-win_amd64.whl (481 kB)
Collecting wasabi<1.2.0,>=0.9.1
  Using cached wasabi-1.1.2-py3-none-any.whl (27 kB)
Collecting murmurhash<1.1.0,>=0.28.0
  Using cached murmurhash-1.0.10-cp310-cp310-win_amd64.whl (25 kB)
Collecting smart-open<7.0.0,>=5.2.1
  Using cached smart_open-6.4.0-py3-none-any.whl (57 kB)
Collecting catalogue<2.1.0,>=2.0.6
  Using cached catalogue-2.0.10-py3-none-any.whl (17 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0
  Using cached spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Collecting requests<3.0.0,>=2.13.0
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4
  Using cached pydantic-1.10.13-cp310-cp310-win_amd64.whl (2.1 MB)
Collecting preshed<3.1.0,>=3.0.2
  Using cached preshed-3.0.9-cp310-cp310-win_amd64.whl (122 kB)
Collecting thinc<8.2.0,>=8.1.8
  Using cached thinc-8.1.12-cp310-cp310-win_amd64.whl (1.5 MB)
Collecting spacy-legacy<3.1.0,>=3.0.11
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Collecting typer<0.8.0,>=0.3.0
  Using cached typer-0.7.0-py3-none-any.whl (38 kB)
Collecting dora-search
  Using cached dora_search-0.1.12.tar.gz (87 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting colorlog
  Using cached colorlog-6.7.0-py2.py3-none-any.whl (11 kB)
Collecting antlr4-python3-runtime==4.9.*
  Using cached antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
  Preparing metadata (setup.py) ... done
Collecting omegaconf<2.4,>=2.2
  Using cached omegaconf-2.3.0-py3-none-any.whl (79 kB)
Collecting filelock
  Using cached filelock-3.12.4-py3-none-any.whl (11 kB)
Collecting sympy
  Downloading sympy-1.12-py3-none-any.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 6.4 MB/s eta 0:00:00
Collecting typing-extensions
  Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Collecting networkx
  Downloading networkx-3.1-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 6.0 MB/s eta 0:00:00
Collecting fsspec
  Using cached fsspec-2023.9.2-py3-none-any.whl (173 kB)
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting pyyaml>=5.1
  Using cached PyYAML-6.0.1-cp310-cp310-win_amd64.whl (145 kB)
Collecting regex!=2019.12.17
  Using cached regex-2023.10.3-cp310-cp310-win_amd64.whl (269 kB)
Collecting tokenizers<0.15,>=0.14
  Using cached tokenizers-0.14.1-cp310-none-win_amd64.whl (2.2 MB)
Collecting safetensors>=0.3.1
  Using cached safetensors-0.4.0-cp310-none-win_amd64.whl (277 kB)
Collecting lameenc>=1.2
  Using cached lameenc-1.6.1-cp310-cp310-win_amd64.whl (148 kB)
Collecting openunmix
  Using cached openunmix-1.2.1-py3-none-any.whl (46 kB)
Collecting matplotlib~=3.0
  Using cached matplotlib-3.8.0-cp310-cp310-win_amd64.whl (7.6 MB)
Collecting altair<6.0,>=4.2.0
  Using cached altair-5.1.2-py3-none-any.whl (516 kB)
Collecting uvicorn>=0.14.0
  Using cached uvicorn-0.23.2-py3-none-any.whl (59 kB)
Collecting aiofiles<24.0,>=22.0
  Using cached aiofiles-23.2.1-py3-none-any.whl (15 kB)
Collecting semantic-version~=2.0
  Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Collecting pandas<3.0,>=1.0
  Using cached pandas-2.1.1-cp310-cp310-win_amd64.whl (10.7 MB)
Collecting ffmpy
  Using cached ffmpy-0.3.1.tar.gz (5.5 kB)
  Preparing metadata (setup.py) ... done
Collecting websockets<12.0,>=10.0
  Using cached websockets-11.0.3-cp310-cp310-win_amd64.whl (124 kB)
Collecting fastapi
  Using cached fastapi-0.103.2-py3-none-any.whl (66 kB)
Collecting python-multipart
  Using cached python_multipart-0.0.6-py3-none-any.whl (45 kB)
Collecting orjson~=3.0
  Using cached orjson-3.9.7-cp310-none-win_amd64.whl (134 kB)
Collecting importlib-resources<7.0,>=1.3
  Using cached importlib_resources-6.1.0-py3-none-any.whl (33 kB)
Collecting pydub
  Using cached pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Collecting gradio-client==0.6.0
  Using cached gradio_client-0.6.0-py3-none-any.whl (298 kB)
Collecting markupsafe~=2.0
  Using cached MarkupSafe-2.1.3-cp310-cp310-win_amd64.whl (17 kB)
Collecting pillow<11.0,>=8.0
  Using cached Pillow-10.0.1-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting httpx
  Using cached httpx-0.25.0-py3-none-any.whl (75 kB)
Collecting scikit-learn>=0.20.0
  Using cached scikit_learn-1.3.1-cp310-cp310-win_amd64.whl (9.3 MB)
Collecting lazy-loader>=0.1
  Using cached lazy_loader-0.3-py3-none-any.whl (9.1 kB)
Collecting pooch>=1.0
  Using cached pooch-1.7.0-py3-none-any.whl (60 kB)
Collecting joblib>=0.14
  Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
Collecting numba>=0.51.0
  Using cached numba-0.58.0-cp310-cp310-win_amd64.whl (2.6 MB)
Collecting audioread>=2.1.9
  Using cached audioread-3.0.1-py3-none-any.whl (23 kB)
Collecting scipy>=1.2.0
  Using cached scipy-1.11.3-cp310-cp310-win_amd64.whl (44.1 MB)
Collecting msgpack>=1.0
  Using cached msgpack-1.0.7-cp310-cp310-win_amd64.whl (222 kB)
Collecting soundfile>=0.12.1
  Using cached soundfile-0.12.1-py2.py3-none-win_amd64.whl (1.0 MB)
Collecting decorator>=4.3.0
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting soxr>=0.3.2
  Using cached soxr-0.3.7-cp310-cp310-win_amd64.whl (184 kB)
Collecting docopt>=0.6.2
  Using cached docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting lightning-utilities>=0.8.0
  Using cached lightning_utilities-0.9.0-py3-none-any.whl (23 kB)
Collecting xformers
  Using cached xformers-0.0.21-cp310-cp310-win_amd64.whl (97.5 MB)
  Using cached xformers-0.0.20-cp310-cp310-win_amd64.whl (97.6 MB)
Collecting pyre-extensions==0.0.29
  Downloading pyre_extensions-0.0.29-py3-none-any.whl (12 kB)
Collecting xformers
  Using cached xformers-0.0.19-cp310-cp310-win_amd64.whl (96.7 MB)
  Downloading xformers-0.0.18-cp310-cp310-win_amd64.whl (112.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.3/112.3 MB 5.3 MB/s eta 0:00:00
Collecting pyre-extensions==0.0.23
  Downloading pyre_extensions-0.0.23-py3-none-any.whl (11 kB)
Collecting xformers
  Downloading xformers-0.0.17-cp310-cp310-win_amd64.whl (112.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.6/112.6 MB 5.2 MB/s eta 0:00:00
  Downloading xformers-0.0.16-cp310-cp310-win_amd64.whl (40.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.0/40.0 MB 6.1 MB/s eta 0:00:00
  Downloading xformers-0.0.13.tar.gz (292 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 292.5/292.5 kB 4.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\bayus\AppData\Local\Temp\pip-install-nz6ycovj\xformers_5e722d04a7d34dd8b3069d58fb05c922\setup.py", line 18, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(venv) D:\Installers\audiocraft>pip uninstall torch -y
WARNING: Skipping torch as it is not installed.

(venv) D:\Installers\audiocraft>pip uninstall torchvision -y
WARNING: Skipping torchvision as it is not installed.

(venv) D:\Installers\audiocraft>pip uninstall torchaudio -y
WARNING: Skipping torchaudio as it is not installed.

(venv) D:\Installers\audiocraft>pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch
  Using cached https://download.pytorch.org/whl/cu118/torch-2.1.0%2Bcu118-cp310-cp310-win_amd64.whl (2722.7 MB)
Collecting torchvision
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.16.0%2Bcu118-cp310-cp310-win_amd64.whl (5.0 MB)
Collecting torchaudio
  Using cached https://download.pytorch.org/whl/cu118/torchaudio-2.1.0%2Bcu118-cp310-cp310-win_amd64.whl (3.9 MB)
Collecting sympy
  Using cached https://download.pytorch.org/whl/sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting typing-extensions
  Using cached https://download.pytorch.org/whl/typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting fsspec
  Using cached https://download.pytorch.org/whl/fsspec-2023.4.0-py3-none-any.whl (153 kB)
Collecting filelock
  Using cached https://download.pytorch.org/whl/filelock-3.9.0-py3-none-any.whl (9.7 kB)
Collecting networkx
  Using cached https://download.pytorch.org/whl/networkx-3.0-py3-none-any.whl (2.0 MB)
Collecting jinja2
  Using cached https://download.pytorch.org/whl/Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached https://download.pytorch.org/whl/Pillow-9.3.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting numpy
  Downloading https://download.pytorch.org/whl/numpy-1.24.1-cp310-cp310-win_amd64.whl (14.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 6.4 MB/s eta 0:00:00
Collecting requests
  Using cached https://download.pytorch.org/whl/requests-2.28.1-py3-none-any.whl (62 kB)
Collecting MarkupSafe>=2.0
  Using cached https://download.pytorch.org/whl/MarkupSafe-2.1.2-cp310-cp310-win_amd64.whl (16 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached https://download.pytorch.org/whl/urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
Collecting certifi>=2017.4.17
  Using cached https://download.pytorch.org/whl/certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting charset-normalizer<3,>=2
  Using cached https://download.pytorch.org/whl/charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Using cached https://download.pytorch.org/whl/idna-3.4-py3-none-any.whl (61 kB)
Collecting mpmath>=0.19
  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, fsspec, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision, torchaudio
Successfully installed MarkupSafe-2.1.2 certifi-2022.12.7 charset-normalizer-2.1.1 filelock-3.9.0 fsspec-2023.4.0 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 networkx-3.0 numpy-1.24.1 pillow-9.3.0 requests-2.28.1 sympy-1.12 torch-2.1.0+cu118 torchaudio-2.1.0+cu118 torchvision-0.16.0+cu118 typing-extensions-4.4.0 urllib3-1.26.13

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(venv) D:\Installers\audiocraft>pip install -U --pre xformers
Collecting xformers
  Downloading xformers-0.0.23.dev639-cp310-cp310-win_amd64.whl (97.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.6/97.6 MB 5.5 MB/s eta 0:00:00
Requirement already satisfied: torch==2.1.0 in d:\installers\audiocraft\venv\lib\site-packages (from xformers) (2.1.0+cu118)
Requirement already satisfied: numpy in d:\installers\audiocraft\venv\lib\site-packages (from xformers) (1.24.1)
Requirement already satisfied: filelock in d:\installers\audiocraft\venv\lib\site-packages (from torch==2.1.0->xformers) (3.9.0)
Requirement already satisfied: networkx in d:\installers\audiocraft\venv\lib\site-packages (from torch==2.1.0->xformers) (3.0)
Requirement already satisfied: fsspec in d:\installers\audiocraft\venv\lib\site-packages (from torch==2.1.0->xformers) (2023.4.0)
Requirement already satisfied: typing-extensions in d:\installers\audiocraft\venv\lib\site-packages (from torch==2.1.0->xformers) (4.4.0)
Requirement already satisfied: sympy in d:\installers\audiocraft\venv\lib\site-packages (from torch==2.1.0->xformers) (1.12)
Requirement already satisfied: jinja2 in d:\installers\audiocraft\venv\lib\site-packages (from torch==2.1.0->xformers) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in d:\installers\audiocraft\venv\lib\site-packages (from jinja2->torch==2.1.0->xformers) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in d:\installers\audiocraft\venv\lib\site-packages (from sympy->torch==2.1.0->xformers) (1.3.0)
Installing collected packages: xformers
Successfully installed xformers-0.0.23.dev639

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(venv) D:\Installers\audiocraft>python .\demos\musicgen_app.py --inbrowser
Traceback (most recent call last):
  File "D:\Installers\audiocraft\demos\musicgen_app.py", line 21, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

(venv) D:\Installers\audiocraft>
```

**Comment by FurkanGozukara** [comment]
sadly it is stupid repo owners error

still trying to solve over 1 hour :(

**Comment by FurkanGozukara** [comment]
good news

I have found the source of error

updated 1 click auto installer : https://www.patreon.com/posts/84334460

also updated github readme file as well

**Comment by gotanidea** [comment]
Thank you!
