### ISSUE TITLE
AttributeError: module 'torch.nn.utils.parametrizations' has no attribute 'weight_norm'

### ISSUE THREAD

**Issue by HydraBucket** [FurkanGozukara/Stable-Diffusion#38]
When trying to run tortoise-tts-fast, I recieve this error

(venv) E:\X\Voice Training\tortoise-tts-fast>python "E:\X\Voice Training\tortoise-tts-fast\scripts\tortoise_tts.py" --preset high_quality --ar_checkpoint "E:\X\Voice Training\DL-Art-School\experiments\Matthew_VC\models\875_gpt.pth" "Hello. Can you hear me? Is this thing on?."
Traceback (most recent call last):
  File "E:\X\Voice Training\tortoise-tts-fast\scripts\tortoise_tts.py", line 240, in <module>
    from tortoise.inference import (
  File "E:\X\Voice Training\tortoise-tts-fast\tortoise\inference.py", line 167, in <module>
    vfixer = VoiceFixer()
  File "E:\X\Voice Training\tortoise-tts-fast\venv\lib\site-packages\voicefixer\base.py", line 13, in __init__
    self._model = voicefixer_fe(channels=2, sample_rate=44100)
  File "E:\X\Voice Training\tortoise-tts-fast\venv\lib\site-packages\voicefixer\restorer\model.py", line 180, in __init__
    self.vocoder = Vocoder(sample_rate=44100)
  File "E:\X\Voice Training\tortoise-tts-fast\venv\lib\site-packages\voicefixer\vocoder\base.py", line 19, in __init__
    self._load_pretrain(Config.ckpt)
  File "E:\X\Voice Training\tortoise-tts-fast\venv\lib\site-packages\voicefixer\vocoder\base.py", line 25, in _load_pretrain
    self.model = Generator(Config.cin_channels)
  File "E:\X\Voice Training\tortoise-tts-fast\venv\lib\site-packages\voicefixer\vocoder\model\generator.py", line 34, in __init__
    nn.utils.parametrizations.weight_norm(
AttributeError: module 'torch.nn.utils.parametrizations' has no attribute 'weight_norm'"

**Comment by FurkanGozukara** [comment]
Hello. Tortoise is very sensitive to setup. You have space in your folder name. So do a fresh install in a new folder
Moreover coqui is much better for voice clone and inference. many times faster

I am preparing a tutorial hopefully but not ready yet. I can share my scripts and knowledge for 150$ private lecture

**Comment by itswalli** [comment]
Unfortunately, that doesn't help.

I have exactly the same problem and can't figure out how to fix it. I am very sure that it doesn't have anything to do with spaces in folder names, because in my case, there were no spaces at all. Furthermore, I tried to reproduce this error on another system and I received the very same erro, so it seems to be some global problem.

**Comment by itswalli** [comment]
lol, might be that I just fixed it. Seems like we need an older version of voicefixer. Try:
`pip uninstall voicefixer
pip install voicefixer==0.1.2`
