### ISSUE TITLE
Can't Swap face in video.

### ISSUE THREAD

**Issue by BhadurAli** [FurkanGozukara/Stable-Diffusion#46]
Hello, I have been using collab from past few months and it working smoothly until today. when I want to change the face it give me this error, can you fix this!

/content/roop
Traceback (most recent call last):
  File "/content/roop/run.py", line 3, in <module>
    from roop import core
  File "/content/roop/roop/core.py", line 20, in <module>
    import roop.ui as ui
  File "/content/roop/roop/ui.py", line 15, in <module>
    from roop.predictor import predict_frame, clear_predictor
  File "/content/roop/roop/predictor.py", line 3, in <module>
    import opennsfw2
  File "/usr/local/lib/python3.10/dist-packages/opennsfw2/__init__.py", line 4, in <module>
    from ._inference import Aggregation
  File "/usr/local/lib/python3.10/dist-packages/opennsfw2/_inference.py", line 12, in <module>
    from keras import KerasTensor, Model  # type: ignore
ImportError: cannot import name 'KerasTensor' from 'keras' (/usr/local/lib/python3.10/dist-packages/keras/__init__.py)

**Comment by FurkanGozukara** [comment]
@BhadurAli hello just made update and fixed check it out
